#!/bin/bash
# Project Development Skills — Multi-Platform Installer
# Compatible with Hermes Agent, OpenCode, and Claude Code on Unix-like hosts.
#
# Destination contract:
#   A platform is installed only when its existing parent root is present:
#     Hermes:   $HOME/.hermes/skills/software-development
#     OpenCode: $HOME/.config/opencode/skills
#     Claude:   $HOME/.claude/commands
#   The Hermes CLI is installed (when $HOME/.hermes exists) at
#   $HOME/.hermes/bin/{pd,pd.py,pd_fleet/}. No platform root is bootstrapped.
#   Each skill destination has a manifest recording only files/directories owned
#   by this installer; stale entries in that manifest are removed on upgrade.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
SKILLS_DIR="$REPO_DIR/skills"
HERMES_ROOT="$HOME/.hermes"
OPENCODE_ROOT="$HOME/.config/opencode"
CLAUDE_ROOT="$HOME/.claude"
HERMES_DIR="$HERMES_ROOT/skills/software-development"
OPENCODE_DIR="$OPENCODE_ROOT/skills"
CLAUDE_DIR="$CLAUDE_ROOT/commands"
MANIFEST_NAME=".pd-installer-manifest"

# The associative array is intentionally populated only after destination
# discovery, so collision checking never creates a platform directory.
declare -A CLAUDE_SOURCES=()

strip_hermes_metadata() {
    python3 - "$1" <<'PY'
from pathlib import Path
import re
import sys
path = Path(sys.argv[1])
content = path.read_text()
content = re.sub(r"metadata:\n  hermes:\n    tags: \[.*?\]\n    related_skills: \[.*?\]\n", "", content, count=1)
path.write_text(content)
PY
}

strip_claude_optional_references() {
    python3 - "$1" <<'PY'
from pathlib import Path
import sys
path = Path(sys.argv[1])
lines = path.read_text().splitlines(keepends=True)
path.write_text(''.join(line for line in lines if 'references/' not in line))
PY
}

preflight_flat_names() {
    local skill_file skill_dir skill_name
    while IFS= read -r -d '' skill_file; do
        skill_dir="$(dirname "$skill_file")"
        skill_name="$(basename "$skill_dir")"
        if [[ -n "${CLAUDE_SOURCES[$skill_name]:-}" && "${CLAUDE_SOURCES[$skill_name]}" != "$skill_dir" ]]; then
            printf 'ERROR: Claude flat-name collision for %q:\n  %s\n  %s\n' \
                "$skill_name" "${CLAUDE_SOURCES[$skill_name]}" "$skill_dir" >&2
            return 1
        fi
        CLAUDE_SOURCES[$skill_name]="$skill_dir"
    done < <(find "$SKILLS_DIR" -type f -name SKILL.md -print0)
}

# Manifest entries are generated by this installer, not inferred from arbitrary
# destination contents. This is what allows user-owned files to survive.
remove_owned_entries() {
    local destination="$1" manifest="$destination/$MANIFEST_NAME"
    local kind relative path
    [[ -f "$manifest" ]] || return 0
    while IFS=$'\t' read -r kind relative; do
        [[ -n "$relative" ]] || continue
        case "$relative" in
            /*|../*|*/../*|.|..)
                printf 'ERROR: invalid installer manifest entry: %q\n' "$relative" >&2
                return 1
                ;;
        esac
        path="$destination/$relative"
        case "$kind" in
            dir) rm -rf -- "$path" ;;
            file) rm -f -- "$path" ;;
            *) printf 'ERROR: invalid installer manifest kind: %q\n' "$kind" >&2; return 1 ;;
        esac
    done < "$manifest"
    rm -f -- "$manifest"
}

begin_manifest() {
    local destination="$1"
    mkdir -p "$destination"
    : > "$destination/$MANIFEST_NAME.tmp"
}

finish_manifest() {
    local destination="$1"
    mv -f -- "$destination/$MANIFEST_NAME.tmp" "$destination/$MANIFEST_NAME"
}

install_hermes() {
    local skill_dir="$1" relative_dir="$2"
    mkdir -p "$HERMES_DIR/$(dirname "$relative_dir")"
    rm -rf "$HERMES_DIR/$relative_dir"
    cp -a "$skill_dir" "$HERMES_DIR/$relative_dir"
    printf 'dir\t%s\n' "$relative_dir" >> "$HERMES_DIR/$MANIFEST_NAME.tmp"
}

install_opencode() {
    local skill_dir="$1" relative_dir="$2"
    mkdir -p "$OPENCODE_DIR/$(dirname "$relative_dir")"
    rm -rf "$OPENCODE_DIR/$relative_dir"
    cp -a "$skill_dir" "$OPENCODE_DIR/$relative_dir"
    strip_hermes_metadata "$OPENCODE_DIR/$relative_dir/SKILL.md"
    printf 'dir\t%s\n' "$relative_dir" >> "$OPENCODE_DIR/$MANIFEST_NAME.tmp"
}

install_claude() {
    local skill_dir="$1" skill_name="$3"
    mkdir -p "$CLAUDE_DIR"
    cp "$skill_dir/SKILL.md" "$CLAUDE_DIR/$skill_name.md"
    strip_hermes_metadata "$CLAUDE_DIR/$skill_name.md"
    strip_claude_optional_references "$CLAUDE_DIR/$skill_name.md"
    printf 'file\t%s.md\n' "$skill_name" >> "$CLAUDE_DIR/$MANIFEST_NAME.tmp"
}

run_for_each_skill() {
    local installer="$1" skill_file skill_dir relative_dir skill_name
    while IFS= read -r -d '' skill_file; do
        skill_dir="$(dirname "$skill_file")"
        relative_dir="${skill_dir#"$SKILLS_DIR"/}"
        relative_dir="${relative_dir%/}"
        skill_name="$(basename "$skill_dir")"
        "$installer" "$skill_dir" "$relative_dir" "$skill_name"
    done < <(find "$SKILLS_DIR" -type f -name SKILL.md -print0)
}

install_hermes_cli() {
    local cli_dir="$HERMES_ROOT/bin"
    mkdir -p "$cli_dir"
    cp "$REPO_DIR/scripts/pd" "$cli_dir/pd"
    cp "$REPO_DIR/scripts/pd.py" "$cli_dir/pd.py"
    rm -rf "$cli_dir/pd_fleet"
    mkdir -p "$cli_dir/pd_fleet"
    while IFS= read -r -d '' package_file; do
        cp "$package_file" "$cli_dir/pd_fleet/$(basename "$package_file")"
    done < <(find "$REPO_DIR/scripts/pd_fleet" -maxdepth 1 -type f -name '*.py' -print0)
    chmod +x "$cli_dir/pd"
}

install_target() {
    local name="$1" destination="$2" installer="$3"
    printf '📦 Installing to %s...\n' "$name"
    remove_owned_entries "$destination"
    begin_manifest "$destination"
    run_for_each_skill "$installer"
    finish_manifest "$destination"
    printf '   ✅ Done\n'
}

echo "🚀 Project Development Skills Installer"
echo "========================================"
[[ -d "$SKILLS_DIR" ]] || { printf 'ERROR: skills source not found: %s\n' "$SKILLS_DIR" >&2; exit 1; }
preflight_flat_names

target_count=0
if [[ -d "$HERMES_ROOT" ]]; then
    target_count=$((target_count + 1))
    install_target "Hermes Agent" "$HERMES_DIR" install_hermes
    install_hermes_cli
    echo "   ✅ CLI installed at $HERMES_ROOT/bin/{pd,pd.py,pd_fleet/}"
fi
if [[ -d "$OPENCODE_ROOT" ]]; then
    target_count=$((target_count + 1))
    install_target "OpenCode" "$OPENCODE_DIR" install_opencode
fi
if [[ -d "$CLAUDE_ROOT" ]]; then
    target_count=$((target_count + 1))
    install_target "Claude Code" "$CLAUDE_DIR" install_claude
fi

if (( target_count == 0 )); then
    printf 'ERROR: no supported destination found. Create one of: %s, %s, or %s\n' \
        "$HERMES_ROOT" "$OPENCODE_ROOT" "$CLAUDE_ROOT" >&2
    exit 2
fi

echo
echo "✅ Installation complete"
echo "Source: $SKILLS_DIR"
echo ""
echo "Usage:"
echo "  Hermes/OpenCode: skill_view(name='pd')"
echo "  Claude: /pd"
